
app: event-driven-architecture-test
service: service-two

provider:
  name: aws
  runtime: nodejs20.x

plugins:
  - serverless-plugin-monorepo

functions:
  second-service:
    handler: index.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:507754063151:my-test-pub-sub-queue
          batchSize: 1
          maximumRetryAttempts: 3
          
