# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: matheusdev20
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: event-driven-architecture-test
# "service" is the name of this project. This will also be added to your AWS resource names.
service: service-two

provider:
  name: aws
  runtime: nodejs20.x

functions:
  second-service:
    handler: handler.hello
