app: event-driven-architecture-test
service: service-one

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sns:Publish
          Resource: arn:aws:sns:us-east-1:507754063151:event-driven-poc

plugins:
  - serverless-plugin-monorepo

functions:
  first-service:
    handler: index.handler
    events:
      - http: GET trigger
    environment:
      SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:507754063151:event-driven-poc"
