# "org" ensures this Service is used with the correct Serverless Framework Access Key.
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: event-driven-architecture-test
# "service" is the name of this project. This will also be added to your AWS resource names.
service: service-one

provider:
  name: aws
  runtime: nodejs20.x

plugins:
  - serverless-plugin-monorepo

functions:
  first-service:
    handler: lambda.handler
    events:
      - http: GET trigger
    environment:
      SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:507754063151:event-driven-poc"

